### ISSUE TITLE
namespace seem to be ignored

### ISSUE THREAD

**Issue by GuiBibeau** [upstash/semantic-cache#5]
Hello! I started using this package recently and it does wonders! I wanted to flag a potential issue with namespaces.

Namespaces in 1.0.3 are mixed and not isolated from each other. Here is a reproduction scenario (including a repo bellow too):

1. Using a common index, create two caches with different name spaces: `semantic-cache-a` and `semantic-cache-b`.
2. Set an item to `semantic-cache-a` key: `what is the capital of france`, value: `The capital of France is Paris.` 
3. The API call has a duration of 1.5s, indicating a call to LLM
4. Try the same query, this time we get a cache hit from `semantic-cache-a`. API call takes 300ms. Working as expected ✅ 
5. Try the same query but use `semantic-cache-b` this time, expecting cache miss. API call takes 350ms, serving the `semantic-cache-a` keys instead of B while the namespace was specified. I would have expected a cache miss:

<img width="891" alt="Screenshot 2024-08-07 at 4 22 24 PM" src="https://github.com/user-attachments/assets/4a3558c3-5fa5-43ce-a62c-f6ce8809cb83">

[See this repo here for details](https://github.com/GuiBibeau/semantic-cache-nextjs/tree/namespaces)

- [both caches are created from the same index DB here](https://github.com/GuiBibeau/semantic-cache-nextjs/blob/namespaces/lib/semantic-cache.ts)
- [This route handles alternating between the caches](https://github.com/GuiBibeau/semantic-cache-nextjs/blob/namespaces/app/api/chat/route.ts)
- [This UI allows changing cache but seems to get resutls from all namespaces.](https://github.com/GuiBibeau/semantic-cache-nextjs/blob/namespaces/components/search-bar.tsx)

**Comment by ogzhanolguncu** [comment]
Hey there, I debugged the issue, and sorry to say that it was on our end. The last release somehow didn’t include namespaces, even though it looked like it did. Now, it’s actually there. I tried it with your code, and it works. All you need to do is bump your `@upstash/semantic-cache` to `1.0.4`.  Let me know if you need any help.

**Comment by GuiBibeau** [comment]
Awesome thanks! I'll close the issue
